set(AL_USDMaya_ROOT "$ENV{REZ_AL_USDMAYA_ROOT}")
set(AL_USDMaya_INCLUDE_DIRS "$ENV{REZ_AL_USDMAYA_ROOT}/include;$ENV{REZ_AL_EVENTSYSTEM_ROOT}/include;$ENV{REZ_AL_USDUTILS_ROOT}/include;$ENV{REZ_AL_MAYAUTILS_ROOT}/include;$ENV{REZ_AL_USDMAYAUTILS_ROOT}/include")
set(AL_USDMaya_LIBRARY_DIRS "$ENV{REZ_AL_USDMAYA_ROOT}/lib")
set(AL_USDMaya_LIBRARIES "")
set(AL_USDMaya_DEFINITIONS "")

set(AL_USDMaya_USE_SYSTEM_INCLUDE_DIRS "FALSE")

list(APPEND CMAKE_PREFIX_PATH $ENV{REZ_AL_USDMAYA_ROOT})

